openapi: 3.1.0

info:
  title: Have a Chat
  description: An API to create chats and send messages to other users. For further information, please see https://github.com/Jat97/HaveAChat.
  version: 0.0.0

servers:
  -url: http://api.haveachat.com
  description: Main server

  -url: http://staging-api.haveachat.com
  description: Testing server

paths:
  /users:
    get:
      summary: A list of users.
      security:
      - logCookie: []
      responses:
        '200':
          description: Returns an array of user objects. The user's own data, as well as the data of the users they have blocked, will be excluded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    contents:
                      $ref: '#/components/schemas/User'
              examples:
                example1:
                  value:
                  - id: 1
                    username: Here2Chat
                    dob: 1983-08-01
                    online: true
                    profile_picture: null
                    display_name: Adam Sutherland
                    hidden: false
                  - id: 2
                    username: ExampleFriend1
                    dob: 1990-03-20
                    online: false
                    profile_picture: https://examplestorage.com/examplestring1/image/upload/examplestring2/image.jpg
                    hidden: true
                  - id: 3
                    username: SampleFriend2
                    dob: 1975-03-17
                    online: false
                    profile_picture: https://examplestorage.com/examplestring3/image/upload/examplestring4/image.jpg
                    hidden: false
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '500':
          $ref: '#/components/responses/ServerError'
  
  /user:
    get:
      summary: Retrieve the logged user's data.
      security:
      - logCookie: []
      responses:
        '200':
          description: Returns an object containing the logged user's data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  logged_user:
                    $ref: '#/components/schemas/User'
                  friends:
                    type: array
                    items: 
                      $ref: '#/components/schemas/User'
                  blocked_users:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserSnippet'
              examples:
                example1:
                  value:
                    logged_user:
                      id: 4
                      username: ABoringUsername
                      dob: 2001-01-10
                      online: true
                      profile_picture: https://examplestorage.com/examplestring5/image/upload/examplestring6/image.jpg
                      hidden: false
                    friends:
                    - id: 2
                      username: ExampleFriend1
                      dob: 1999-03-20
                      online: true
                      profile_picture: https://examplestorage.com/examplestring1/image/upload/examplestring2/image.jpg
                      display_name: John Smith
                      hidden: false
                    - id: 3
                      username: SampleFriend2
                      dob: 1975-07-17
                      online: true
                      profile_picture: https://examplestorage.com/examplestring3/image/upload/examplestring4/image.jpg
                      display_name: Gerald Johnson
                      hidden: false
                    blocked_users:
                    - id: 5
                      username: ABigMeanie
                      profile_picture: https://examplestorage.com/examplestring7/image/upload/examplestring8/image.jpg
                      display_name: David French
                    - id: 6
                      username: YetAnotherMeanie
                      profile_picture: https://examplestorage.com/examplestring9/image/upload/examplestring10/image.jpg
                      display_name: Sarah Jones
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '500':
          $ref: '#/components/responses/ServerError'
          
    delete:
      summary: Delete the logged user's account.
      security:
      - logCookie: []
      responses:
        '200':
          description: Deletes the user's account. All data created by the user, including chats, messages, blocks, and requests, will be deleted as well.
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '500':
          $ref: '#/components/responses/ServerError'
  
  /signup:
    post:
      summary: Create an account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUp'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SignUp'
      responses:
        '201':
          description: The user's account was successfully created.
          headers:
            setCookie:
              schema:
                type: string
                examples:
                  example1:
                    value: usertoken=logged1a2b3c; Path=/api; HttpOnly
        '400':
          description: The user submitted a username or email that was already taken, or their passwords did not match.
          content:
            application/json:
              schemas:
                username:
                  type: string
                display_name:
                  type: string
                dob: 
                  type: string
                email: 
                  type: string
                password:
                  type: string
                confirm:
                  type: string
              examples:
                example1:
                  value:
                    username: This username already exists.
                example2:
                  value:
                    email: This email is already in use.
                example3:
                  value:
                    display: Please enter a display name.
                example4:
                  value:
                    dob: You must be at least 18 to register.
                example5:
                  value:
                    password: Password must be at least 8 characters.
                example6:
                  value:  
                    confirm: Passwords do not match.
        '500':
          $ref: '#/components/schemas/ServerError'
  
  /login:
    post:
      summary: Log into an existing account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogIn'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LogIn'
      responses:
        '200':
          description: The user was successfully logged into their account.
          headers:
            setCookie:
              examples:
                example1:
                  value: usertoken=logged1a2b3c; Path=/api; HttpOnly
        '400':
          description: The user submitted incomplete or incorrect information.
          contents:
            schema:
              type: object
              properties:
                user_error:
                  type: string
                pass_error:
                  type: string
            examples:
              example1:
                value:
                  user_error: This account does not exist.
              example2:
                value:
                  pass_error: The password is incorrect.
  
  /user/picture:
    patch:
      summary: Update the user's profile picture.
      security:
      - logCookie: []
      requestBody:
        content:
          image/jpg:
            schema:
              type: string
              format: base64
          image/png:
            schema:
              type: string
              format: base64
      responses:
        '200':
          description: Returns an object containing the new image's URL.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  updated_user:
                    type: object
                    properties:
                      profile_picture:
                        type: string
              examples:
                example1:
                  value:
                    updated_user:
                      profile_picture: https://examplestorage.com/examplestring5/image/upload/examplestring6/image.jpg
        '401':
          $ref: '#/components/schemas/NotAuthorized'
        '500':
          $ref: '#/components/schemas/ServerError'    
  
  /user/hidden:
    patch:
      summary: Toggle user visibility.
      security:
      - logCookie: []
      responses:
        '200':
          description: Returns an object containing new hidden status. As this endpoint doesn't require a request body, the value of the user's "hidden" property updates based on its initial value.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  hidden_status:
                    type: object
                    properties:
                      id: 
                        type: integer
                        format: int64
                      hidden:
                        type: boolean
              examples:
                example1:
                  value:
                    hidden_status:
                      id: 4
                      hidden: true
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '500':
          $ref: '#/components/responses/ServerError'

  /logout:
    patch:
      summary: End the current session.
      security:
      - logCookie: []
      responses:
        '200':
          description: The user was successfully logged out.
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '500':
          $ref: '#/components/responses/ServerError'

  /unfriend/{username}:
    delete:
      summary: Unfriend another user.
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
        description: The username of the user to unfriend.
      security:
      - logCookie: []
      responses:
        '200':
          description: The user's friend object was deleted. The unfriended user's friend object will also be deleted.
        '401':
          $ref: '#/components/schemas/NotAuthorized'
        '500':
          $ref: '#/components/schemas/ServerError'
        
  /block/{username}:
    post:
      summary: Block another user.
      security:
      - logCookie: []
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
        description: The username of the user to be blocked.
      responses:
        '201':
          description: Returns an object containing the blocked user's data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  new_block:
                    type: object
                    properties:
                      blocked_user:
                        type: integer
                        format: int64
                      blocked_by:
                        type: integer
                        format: int64
              examples:
                example1:
                  value:
                    new_block:
                      blocked_user: 1
                      blocked_by: 4
        '401':
          $ref: '#/components/schemas/NotAuthorized'
        '500':
          $ref: '#/components/schemas/ServerError'
  
  /unblock/{username}:
    delete: 
      summary: Unblock a user.
      security:
      - logCookie: []
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
        description: The username of the selected user.
      responses:
        '200':  
          description: The user was successfully unblocked.
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '500':
          $ref: '#/components/responses/ServerError' 
  
  /chats
    get:
      summary: Retrieve the user's chats, messages, and requests.
      security:
      - logCookie: []
      responses:
        '200': 
          description: Returns an object containing all of the user's active chats, as well as messages and unaccepted chat requests.
          content:
            application/json:
              schema:
                type: object
                properties:
                  chats:
                    type: array
                    items:
                      anyOf:
                      - $ref: '#/components/schemas/Chats'
                      - $ref: '#/components/schemas/Messages'
                      - $ref: '#/components/schemas/ChatRequests'
              examples:
                example1:
                  value:
                    chats:
                    - chat:
                        id: 10
                        user:
                          id: 2
                          username: ExampleFriend1
                          display: John Smith
                          profile_picture: https://examplestorage.com/examplestring1/image/upload/examplestring2/image.jpg
                          online: true
                          hidden: false
                        messages:
                        - id: 20
                          text: Would you like to know a little fun fact?
                          sending_user: 4
                          receiving_user: 2
                          sent: 2025-03-26
                          checked: true
                          image: null
                        - id: 21
                          text: Sure. Tell me a fun fact.
                          sending_user: 2
                          receiving_user: 4
                          sent: 2025-03-27
                          checked: true
                          image: null
                        - id: 22
                          text: This guy holds the record for winning the most electoral votes without winning a presidential election.
                          sending_user: 4
                          receiving_user: 2
                          sent: 2025-03-27
                          checked: false
                          image: https://examplestorage.com/examplestring11/image/upload/examplestring12/william_jennings_bryan.jpg
                      request: null
                    - chat: 
                        id: 11
                        user:
                          id: 3
                          username: SampleFriend2
                          display_name: Gerald Johnson
                          profile_picture: https://examplestorage.com/examplestring3/image/upload/examplestring4/image.jpg
                          online: true
                          hidden: false
                        messages:
                        - id: 23
                          text: "Have you ever watched The Fifth Element? I hear it's great."
                          sending_user: 3
                          receiving_user: 4
                          sent: 2025-04-18
                          checked: false
                          image: null
                      request:
                        id: 30
                        requesting_user: 3
        '401':
          $ref: '#/components/schemas/NotAuthorized'
        '500':
          $ref: '#/components/schemas/ServerError'
  
  /{username}/message:
    post:
      summary: Send another user a message.
      security:
      - logCookie: []
      parameters:
      - in: path
        name: username
        required: true
        schema:
          type: string
        description: The username of the user who will receive the message.
      responses:
        '201':
          description: Returns an object containing the sent message. If the other user does not have a chat associated with the logged-in user, then one will be created for them when the message is sent.
          content:
            application/json:
              schema:
                type: object
                properties:
                  $ref: '#/components/schemas/Message'
              examples:
                example1:
                  value:
                    id: 24
                    text: "Here's another fun fact: William McKinley was the last president to wear a bowtie in his presidential portrait. Crazy, right?"
                    sending_user: 4
                    receiving_user: 2
                    sent: 2025-03-30
                    checked: false
                    image: https://examplestorage.com/examplestring14/image/upload/examplestring15/william_mckinley.jpg
        '401':
          $ref: '#/components/schemas/NotAuthorized'
        '500':
          $ref: '#/components/schemas/ServerError'
  
  /chat/accept/{requestid}:
    post:
      summary: Accept another user's chat request.
      security:
      - logCookie: []
      parameters:
      - in: path
        name: requestid
        required: true
        schema:
          type: integer
        description: The id of the accepted request.
      responses:
        '201':
          description: Returns an object containing the ids of both users. When a request is accepted, both users will be considered friends. As such, the user who sent the request will also have a friend object created for them.
          content: 
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  user1:
                    type: integer
                    format: int64
                  user2:
                    type: integer
                    format: int64
              examples:
                example1:
                  value:
                    id: 40
                    user1: 4
                    user2: 3
        '401':
          $ref: '#/components/schemas/NotAuthorized'
        '500':
          $ref: '#/components/schemas/ServerError'

  /chat/rejected/{requestid}: 
    delete:
      summary: Reject another user's chat request.
      security:
      - logCookie: []
      parameters:
      - in: path
        name: requestid
        required: true
        schema:
          type: integer
        description: The id of the rejected request.
      responses:
        '200':
          description: The chat request was successfully deleted.
        '401':
          $ref: '#/components/schemas/NotAuthorized'
        '500':
          $ref: '#/components/schemas/ServerError'
    
  /chat/{chatid}:
    delete:
      summary: Delete a chat.
      security:
      - logCookie: []
      parameters:
      - in: path
        name: chatid
        required: true
        schema:
          type: integer
        description: The id of the deleted chat.
      responses:
        '200':
          description: The chat was deleted. If the other user has their copy of the chat, then all previous messages will be viewable if a new chat is created. If the other user has deleted their copy, then all messages will be deleted as well.
        '401':
          $ref: '#/components/schemas/NotAuthorized'
        '500':
          $ref: '#/components/schemas/ServerError'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        dob:
          type: string
        online:
          type: boolean
        profile_picture:
          type: string
        display_name:
          type: string
        hidden:
          type: boolean

    SignUp:
      type: object
      properties:
        username:
          type: string
        display_name:
          type: string
        dob:
          type: string
        email:
          type: string
        password:
          type: string
        confirm:
          type: string
    
    LogIn:
      type: object
      properties:
        user:
          type: string
        password:
          type: string

    UserData:
      type: object
      properties:
        id: 
          type: integer
          format: int64
        username:
          type: string
        profile_picture:
          type: string
        display_name:
          type: string
        online: 
          type: boolean
        hidden: 
          type: boolean
    
    UserSnippet:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        profile_picture:
          type: string
        display_name:
          type: string
    
    Chat:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user:
          $ref: '#/components/schemas/UserData'
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
    
    Message:
      type: object
      properties:
        id:
          type: integer
          format: int64
        sending_user:
          type: integer
          format: int64
        receiving_user:
          type: integer
          format: int64
        text:
          type: string
        sent:
          type: string

    ChatRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
        requesting_user:
          type: integer

    securitySchemas:
      logCookie:
        type: apiKey
        in: cookie
        name: usertoken

    responses:
      NotAuthorized:
        description: Token either missing or expired.
      ServerError:
        description: Unexpected server error.